### ISSUE TITLE
Question about the receiving Adafruit feather wireing to raspberry pi.

### ISSUE THREAD

**Issue by fabregas4you** [robertsmarty/adafruit3078gps#1]
Mr. robertsmarty.

This project so cool and I'm tring to right now. 
I might cause you trouble but I have some questions,

>The receiving Adafruit feather is configured to listen to data recieved by the onboard LoRa radio and then write the data to another serial port. 

What is "another serial port" ? 

>This second serial port can be connected to the USB of a computer for debugging. In this setup, I've connected the serial port to a Raspberry Pi which I'm using as an internet gateway,

Is "This second serial port" mean the receiving Adafruit feather's USB MicroB port ?
Thank you for your help in advance.

**Comment by robertsmarty** [comment]
Hi fabregas4you,

You are correct. The receiver uses "Serial" to send data to the attached PC via the USB MicroB port.

The transmitter uses "Serial1" to communicate with the GPS module however you can also use "Serial" to debug using its USB MicroB port.

I hope this helps.

Cheers
